GROUP_BY_INCIDENCE_SIGNATURE: true
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: true
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: true
USE_CVXPY: false
USE_SIMUL_INTEGERIZER: true
control_file_name: controls.csv
data_dir: data
geographies:
- WELT
- STAAT
- ZENSUS1km
- ZENSUS100m
household_id_col: H_ID
household_weight_col: H_GEW
input_table_list:
- filename: seed_households.csv
  index_col: H_ID
  tablename: households
- filename: seed_persons.csv
  tablename: persons
- filename: geo_cross_walk.csv
  tablename: geo_cross_walk
- filename: control_totals_ZENSUS100m.csv
  tablename: ZENSUS100m_control_data
- filename: control_totals_ZENSUS1km.csv
  tablename: ZENSUS1km_control_data
- filename: control_totals_STAAT.csv
  tablename: STAAT_control_data
- filename: control_totals_WELT.csv
  tablename: WELT_control_data
max_expansion_factor: 30
models:
- input_pre_processor
- setup_data_structures
- initial_seed_balancing
- meta_control_factoring
- final_seed_balancing
- integerize_final_seed_weights
- sub_balancing.geography=ZENSUS1km
- sub_balancing.geography=ZENSUS100m
- expand_households
- write_data_dictionary
- write_tables
- write_synthetic_population
output_synthetic_population:
  household_id: household_id
  households:
    columns:
    - H_ID
    filename: synthetic_households.csv
  persons:
    columns:
    - HP_ID
    filename: synthetic_persons.csv
output_tables:
  action: include
  tables:
  - expanded_household_ids
  - summary_ZENSUS100m
  - summary_ZENSUS1km
  - summary_STAAT
  - summary_WELT
  - summary_ZENSUS100m_STAAT
resume_after: null
seed_geography: STAAT
total_hh_control: Insgesamt_Haushalte_Groesse_des_privaten_Haushalts_100m_Gitter_adj_ZENSUS100m_target
